JS Array task
SiarheiTsytrykau/siarheitsytrykau.github.io pull request #4
Opened 2017-04-06 23:36 UTC by SiarheiTsytrykau

2017-04-09 15:53 UTC, NikitaSedyx requested changes

2017-04-09 15:53 UTC, NikitaSedyx commented on arrays/js/arrays.js
> +function isArray1(obj) {
this function doesn't make sense, the main goal of this function to implement smth like `Array.isArray`

2017-04-09 15:53 UTC, NikitaSedyx commented on arrays/js/arrays.js
> +  return typeof obj === "object" && Object.prototype.toString.call(obj) === "[object Array]";
it will work without `typeof obj === "object"`

2017-04-09 15:53 UTC, NikitaSedyx commented on arrays/js/arrays.js
> +  if(!Array.isArray(array)) {
you could use your own function :)

2017-04-09 15:53 UTC, NikitaSedyx commented on arrays/js/arrays.js
> +  return !!value;
it will work without `!!` just `return value`
could you move filter etc to function? onlyTrue is not compact

2017-04-09 15:53 UTC, NikitaSedyx commented on arrays/js/arrays.js
> +  array.splice(startPos, deleteCount);
array is mutated, -1

2017-04-09 15:53 UTC, NikitaSedyx commented on arrays/js/arrays.js
> +function range(from, to, step) {
cases should work:
range(10) [0..9]
range(1, 10) [1..9]
range(1, 10, 3) [1, 4, 7]
range(1, 10, 3, 8, 20) [1, 4, 7]
range(10, null, 3) [0, 3, 6, 9]
range(10, null) the same with range(10)
range(-2, -5) []
range(-5, -2) [-5, -4, -3]
range(-5, -2, 2) [-5, -3]
range(-5, -2, -2) []
range(-5, null, 2) []
range(-5, null, -2) [0, -2, -4]
range(-10, -20, -5) [-10, -15]
range(-10, -20, -5, 20) [-10, -15]
range(-20, -10, -5) []

FYI you should find step and length of result array

2017-04-10 19:30 UTC, closed without merging

2017-04-12 04:56 UTC, NikitaSedyx commented
@SiarheiTsytrykau why is PR closed, should I review it?

2017-04-13 16:51 UTC, SiarheiTsytrykau commented
I'm sorry, i was mistaken. Please review this: https://github.com/SiarheiTsytrykau/siarheitsytrykau.github.io/pull/6