OOP Task
SiarheiTsytrykau/siarheitsytrykau.github.io pull request #7
Opened 2017-05-07 09:20 UTC by SiarheiTsytrykau

Last.fm Web Services

2017-05-07 15:52 UTC, NikitaSedyx requested changes
mostly fine, please look at comments

2017-05-07 15:52 UTC, NikitaSedyx commented on LastFm/js/LastFm.js
> +  var url = this.rootURL + "?method=" + this.package + "." + queryParam + "&api_key=" + this.apiKey + "&format=json";
please look at https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent

2017-05-07 15:52 UTC, NikitaSedyx commented on LastFm/js/Runner.js
> +cherBelive.getInfo(function(response){console.log(response.album)});
it needs some spaces

2017-05-07 15:52 UTC, NikitaSedyx commented on LastFm/index.html
> +</html>
eof

2017-05-07 15:52 UTC, NikitaSedyx commented on LastFm/index.html
> +    <script src="js/LastFm.js" defer></script>
do you really need `defer` here? you don't have `async` attribute

2017-05-08 15:08 UTC, SiarheiTsytrykau commented
Comments fixed

2017-05-10 14:48 UTC, NikitaSedyx approved these changes

2017-05-10 18:14 UTC, merged